name: Cucumber Test
on:
  push:
    branches:
      - karan
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Cucumber tests
        run: |
          ./gradlew cucumber

      - name: Generate JSON report
        run: |
          cucumber --format json --out target/cucumber.json

      - name: Upload report to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber.json

      - name: Send Cucumber report to Slack
        uses: 8398a7/action-slack@v3 # using a more specific Slack action
        with:
          status: always
          fields: workflow,job,commit,repo,ref,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          features: $(jq '.features | length' target/cucumber.json)
          passedFeatures: $(jq '.features[] | select(.status == "passed") | length' target/cucumber.json)
          failedFeatures: $(jq '.features[] | select(.status == "failed") | length' target/cucumber.json)
        message: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Cucumber Test Report"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Total Features:* ${features}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Passed Features:* ${passedFeatures}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Failed Features:* ${failedFeatures}"
                  }
                ]
              }
            ]
          }
