name: Cucumber TestThree
on:
  push:
    branches:
      - karan
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean target directory
        run: mvn clean

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Clean report directory
        run: rm -rf target/*

      - name: Run Cucumber tests
        run: mvn test -Dcucumber.options="--plugin pretty --plugin junit:target/cucumber-report/cucumber.xml"

      - name: Generate JSON report
        run: |
          cucumber --format json --out target/cucumber.json

      - name: Upload report to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber.json

      - name: Send Cucumber report to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Cucumber Test Report"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Total Features:* ${features}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Passed Features:* ${passedFeatures}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed Features:* ${failedFeatures}"
                    }
                  ]
                }
              ]
            }
        env:
          features: $(jq '.features | length' target/cucumber.json)
          passedFeatures: $(jq '.features[] | select(.status == "passed") | length' target/cucumber.json)
          failedFeatures: $(jq '.features[] | select(.status == "failed") | length' target/cucumber.json)
