name: Maven Testerter12
on:
  push:
    branches:
      - karan
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean target directory
        run: mvn clean

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Clean report directory
        run: rm -rf target/*

      - name: Run Maven tests and capture output
        id: maven_tests
        run: mvn test | tee maven_output.txt

      - name: Format and send Maven results to Slack
        run: bash .github/scripts/format_and_send_results.sh
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
