name: Maven Test
on:
  push:
    branches:
      - karan
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean target directory
        run: mvn clean

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Clean report directory
        run: rm -rf target/*

      - name: Run Maven tests and capture output
        id: maven_tests
        run: |
          mvn test | tee maven_output.txt
          TEST_RESULTS=$(grep -A 2 'Results:' maven_output.txt)
          BUILD_SUMMARY=$(grep 'BUILD SUCCESS' maven_output.txt)
          TOTAL_TIME=$(grep 'Total time' maven_output.txt)
          FINISHED_AT=$(grep 'Finished at' maven_output.txt)
          echo "TEST_RESULTS=$TEST_RESULTS" >> $GITHUB_ENV
          echo "BUILD_SUMMARY=$BUILD_SUMMARY" >> $GITHUB_ENV
          echo "TOTAL_TIME=$TOTAL_TIME" >> $GITHUB_ENV
          echo "FINISHED_AT=$FINISHED_AT" >> $GITHUB_ENV

      - name: Format and Output Test Results
        id: format_results
        run: |
          FORMATTED_OUTPUT="Test Results\n"
          FORMATTED_OUTPUT+="${{ env.TEST_RESULTS }}\n"
          FORMATTED_OUTPUT+="Build: ${{ env.BUILD_SUMMARY }}\n"
          FORMATTED_OUTPUT+="Duration: ${{ env.TOTAL_TIME }}\n"
          FORMATTED_OUTPUT+="Finished at: ${{ env.FINISHED_AT }}\n"
          echo "$FORMATTED_OUTPUT" > formatted_report.txt
          cat formatted_report.txt
          echo "::set-output name=formatted_report::$FORMATTED_OUTPUT"

      - name: Send Maven results to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          message: "${{ steps.format_results.outputs.formatted_report }}"
