name: Maven Testthree
on:
  push:
    branches:
      - karan
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean target directory
        run: mvn clean

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Clean report directory
        run: rm -rf target/*

      - name: Run Maven tests and capture output
        id: maven_tests
        run: |
          mvn test | tee maven_output.txt
          TEST_RESULTS=$(grep -A 2 'Results:' maven_output.txt | sed 's/
          \[INFO\]
            //g')
         BUILD_SUMMARY=$(grep 'BUILD SUCCESS' maven_output.txt | sed 's/
  
         \[INFO\]
  
          //g')
         TOTAL_TIME=$(grep 'Total time' maven_output.txt | sed 's/
  
         \[INFO\]
  
         //g')
         FINISHED_AT=$(grep 'Finished at' maven_output.txt | sed 's/
  
         \[INFO\]
  
         //g')
          FORMATTED_OUTPUT="*Test Results*\n"
          FORMATTED_OUTPUT+="$TEST_RESULTS\n"
          FORMATTED_OUTPUT+="*Build:* $BUILD_SUMMARY\n"
          FORMATTED_OUTPUT+="*Duration:* $TOTAL_TIME\n"
          FORMATTED_OUTPUT+="*Finished at:* $FINISHED_AT\n"
          echo "$FORMATTED_OUTPUT" > formatted_report.txt
          cat formatted_report.txt

      - name: Send Maven results to Slack
        run: |
            SLACK_MESSAGE=$(cat formatted_report.txt)
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${SLACK_MESSAGE}\"}" ${{ secrets.SLACK_WEBHOOK }}

  
  
  
  
  
  
  
  
  
  
