name: Cucumber Tests
on:
  push:
   branches:
    - karan
  pull_request:
  branches:
    - karan
jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
         java-version: 11
         distribution: 'adopt'
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Clean target directory
      run: mvn clean
    - name: Install Maven dependencies
      run: mvn install -DskipTests
    - name: Clean report directory
      run: rm -rf target/cucumber-report/*
    - name: Run Cucumber tests
      run: mvn test -Dcucumber.options="--plugin pretty --plugin junit:target/cucumber-report/cucumber.xml"
    - name: Convert JUnit XML to JSON
      run: |
        npm install junit2json
        node -e "const { parse } = require('junit2json'); const fs = require('fs'); const xml = fs.readFileSync('target/cucumber-report/cucumber.xml', 'utf8'); const json = parse(xml); fs.writeFileSync('target/cucumber-report/cucumber.json', JSON.stringify(json, null, 2));"
    - name: Upload Cucumber test results (XML)
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-results-xml
        path: target/cucumber-report/cucumber.xml
    - name: Upload Cucumber test results (JSON)
      uses: actions/upload-artifact@v3
      with:
       name: cucumber-results-json
       path: target/cucumber-report/cucumber.json