name: Run Cucumber Tests and Send Results to Slack

on:
  push:
    branches:
      - karan

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run Cucumber tests
        run: mvn test

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Send test results to Slack
        if: always() # Ensure this step runs regardless of previous step outcomes
        run: bash send_report.sh ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
