name: Test karan

on:
  workflow_run:
    workflows: ["Cucumber Tests"]
    types: [completed]

jobs:
#  build:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js 16.x
#        uses: actions/setup-node@v2
#        with:
#          node-version: 16.x
#      - run: npm install
#      - run: npm test
#      - run: pm2 restart app-name
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Install dependencies
#        run: npm install
#      - name: Build
#        run: npx tsc
#      - name: Send Slack Notification (Results)
#        run: npx slack-ctrf results ctrf/ctrf-report.json
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#      - name: Send Slack Notification (Flaky)
#        run: npx slack-ctrf flaky ctrf/ctrf-report.json
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  testing:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
#
#      - name: Build
#        run: npm test
      - name: Convert
        run: npx junit-to-ctrf target/cucumber-report/cucumber.xml

      - name: Send Slack Notification (Results)
        run: npx slack-ctrf results ctrf/ctrf-report.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Notification (Flaky)
        run: npx slack-ctrf flaky ctrf/ctrf-report.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
