name: Run Regression Tests and Generate Allure Report

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-test:
    regressiont001:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: styfle/cancel-workflow-action@0.10.0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        id: tests
        run: mvn clean -D surefire.rerunFailingTestsCount=2 test -D cucumber.filter.tags=@regression_T001_504_Initial_Evaluation_And_Meeting_2_1

      - name: Publish Cucumber Report artifact
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber.html

      - name: Publish Allure Report artifact
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: allure-report
          path: target/allure-results/

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
