name: Build and Run Feature Files

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          wrapper-cache-enabled: true

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Cucumber Tests
        run: ./gradlew cucumber

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/reports/allure-report
