name: Cucumber Test23
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Cucumber tests
        run: |
          ./gradlew cucumber

      - name: Generate JSON report
        run: |
          cucumber --format json --out report.json

      - name: Upload report to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: report.json

      - name: Send report to Slack
        uses: slack/webhook@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Cucumber Test Report"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Total Features:* ${features}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Passed Features:* ${passedFeatures}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed Features:* ${failedFeatures}"
                    }
                  ]
                }
              ]
            }
          env:
            features: $(jq '.features | length' report.json)
            passedFeatures: $(jq '.features[] | select(.status == "passed") | length' report.json)
            failedFeatures: $(jq '.features[] | select(.status == "failed") | length' report.json)
