#name: Send Cucumber Execution Results to Slack
#
#on:
#  workflow_run:
#    workflows: ["Cucumber Tests"]
#    types: [completed]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Java
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '11'  # Specify the Java version you need
#
#      - name: Verify CucumberReportParser.java existence
#        run: ls -la src/test/java/utils
#
#      - name: Compile Java program
#        run: javac src/test/java/utils/CucumberReportParser.java
#
#      - name: Run Java program
#        id: run-parser
#        run: |
#          java -cp src/test/java utils.CucumberReportParser > report.txt
#          cat report.txt
#
#      - name: Send results to Slack
#        uses: slackapi/slack-github-action@v2.0.0
#        with:
#          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
#          webhook-type: 'incoming-webhook'
#          payload: |
#            {
#              "attachments": [
#                {
#                  "title": "Cucumber Test Results",
#                  "text": "$(cat report.txt)",
#                  "color": "#36a64f"
#                }
#              ]
#            }
